version: '3'
services:
  web:
    build: frontend/
    ports:
    - "3000:3000"
    volumes:
    - ./frontend/src:/usr/src/app/src
    - ./frontend/public:/usr/src/app/public
    command: yarn start
  nginx:
    build: nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    command: nginx -g 'daemon off;'
    