version: '3'
services:
  web:
    build: frontend/
    volumes:
    - ./frontend/src:/usr/src/app/src
    - ./frontend/public:/usr/src/app/public
    command: yarn start
  nginx:
    build: nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    command: nginx -g 'daemon off;'
  backend:
    build: backend/
    restart: always
    volumes:
      - ./backend/index.js:/usr/src/app/index.js
      - ./backend/app:/usr/src/app/app/
    command: |
            bash -c "
            pm2 start index.js --watch --no-daemon;"
  postgres:
    build: postgres/
    command: /etc/init.d/postgresql start
    restart: always
    volumes:
      - ./postgres/data/:/etc/postgresql
      - ./postgres/logs/:/var/log/postgresql
      - ./postgres/lib/:/var/lib/postgresql
