version: '3'
services:
  frontend:
    image: gcr.io/michaelgreen/frontend
    build: frontend/
    volumes:
    - ./frontend/src:/usr/src/app/src
    - ./frontend/public:/usr/src/app/public
    command: yarn start
  nginx:
    image: gcr.io/michaelgreen/nginx
    build: nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    command: nginx -g 'daemon off;'
  backend:
    image: gcr.io/michaelgreen/backend
    build: backend/
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./backend/app:/usr/src/app/app/
    command: |
            bash -c "pm2 start app/index.js --watch --no-daemon;"
  mysql:
    image: gcr.io/michaelgreen/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql/data/:/var/lib/mysql