apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    service: frontend
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  service: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - args:
        - "yarn"
        - "start"
        image: gcr.io/michaelgreen/frontend
        imagePullPolicy: Always
        name: frontend
        resources: {}
        ports:
        - containerPort: 3000
      restartPolicy: Always
status: {}