apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website
  annotations:
    kubernetes.io/ingress.global-static-ip-name: website
  labels:
    app: hello
spec:
  backend:
    serviceName: frontend
    servicePort: 3000