apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}